### PR TITLE
More geometry

### PR DESCRIPTION
**Pull request by anitagraham**
Thumbnails can now use gravity and offsets
+-x+-y - offsets for cropping
gravity codes: #c, #n, #s, #e, #w, #ne, #nw, #se, #sw

Refactored processors so that input and output option processing uses
common code.

Using separate positional and keyword arguments where possible

Tests passing with Ruby 2.7.4

### CODE REVIEW

**Comment by mreq** [comment]
@anitagraham This is great! :+1:  I've done [similar](https://github.com/sinfin/dragonfly_libvips/commits/mreq/crop) (but much less complete) but abandoned it to use your fork (didn't notice it before I went to open my PR :pensive:).

**Comment by tomasc** [comment]
@anitagraham yes, thank you! Let me know when you are ready with it and I can merge and release new version.

**Comment by mreq** [comment]
I've added two fixes in a PR to @anitagraham repo https://github.com/anitagraham/dragonfly_libvips/pull/1. Otherwise I see it as good to go :+1:

**Comment by tomasc** [comment]
Thanks @anitagraham and @mreq !

**Comment by mreq** [comment]
@tomasc Note that while the PR is amazing there are still plenty of issues with the version in this PR. See https://github.com/anitagraham/dragonfly_libvips/pull/1 I'll try to cleanup https://github.com/sinfin/dragonfly_libvips/tree/more_geometry and make a PR here.

**Comment by tomasc** [comment]
@mreq yes, thank you, I noticed! It would be very helpful if you can take a look at it.

**Pull request merged**
