### PR TITLE
Add jp2k  et al to FORMATS_WITHOUT_PROFILE_SUPPORT

### PR DESCRIPTION
**Pull request by anitagraham**
### FORMATS_WITHOUT_PROFILE_SUPPORT  now includes `jpc jpt jp2 j2c j2k`. 

These formats all triggered the same error when running tests. Checking the [rubydocs](https://www.rubydoc.info/gems/ruby-vips/Vips/Image#jp2ksave-instance_method) confirmed that `jp2ksave` and its friends `jp2ksave_buffer` and `jp2ksave_target` don't have a profile option, while savers for formats like `jpeg` and `png` do.

### In addition, while running tests
- Added ** when using` DragonflyLibvips.symbolize_keys` as an arg. 
- Changed tests to use `_(result.property).must` as suggested by minitest. 

### Also
My local system is still getting test failures for `encode` converting anything to .raw

I'll open another issue for that.

### CODE REVIEW

**Comment by tomasc** [comment]
Thanks @anitagraham! Let me know when ready, and I'll merge and release new version.

**Comment by anitagraham** [comment]
Added raw to the unsupported output formats.

`encode_test.tb` was failing with `Minitest::UnexpectedError:         Vips::Error: VipsForeignSave: ".raw" is not a known buffer format`, as described in #17 
 
Checking with  `vips -l | grep _target` as advised (on stackoverflow) does not include raw as one of the targets.
On the other hand, rubydocs lists `VipsImage.rawsave`.  Maybe I will rethink this.

**Comment by anitagraham** [comment]
So, it appears that ruby-vips has `VipsForeignSaveRaw` and `VipsForeignSaveRawFd` (saves to file and to file descriptor), but not `VipsForeignSaveRawBuffer` (according to `vips -l | grep raw`. ( vips-8.11.3-Wed Aug 11 09:29:27 UTC 2021).

Encode (and all the processors) return a buffer. 
Perhaps it is just a matter of asking for `VipsForeignSaveRawBuffer` to be added to ruby-vips.

**Comment by tomasc** [comment]
Thanks @anitagraham!

**Pull request merged**
